name: Build on pr
on: [pull_request, push] # change to only pull_request after testing
jobs:
    Create-Plugin-Zip:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repo
              uses: actions/checkout@v4
            - name: Use node
              uses: actions/setup-node@v3
            - name: npm install build export
              run: |
                  npm i
                  npm run build
                  npm run export
            - name: create plugin directory
              run: |
                  cd dist
                  unzip contacts-manager.zip
                  rm contacts-manager.zip
            - name: Upload plugin zip as artifact
              uses: actions/upload-artifact@v3
              with:
                  name: contacts-manager
                  path: dist
